name: Build and Push ml_platform image to Harbor

on:
  push:
    branches:
      - "master"
  repository_dispatch:
    types:
      - dispatch-build

jobs:
  harbor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Docker Build & Push Action
        uses: mr-smithers-excellent/docker-build-push@v6.4
        with:
          image: usatlas/ml-platform
          tags: latest, ${{ github.sha }}
          registry: hub.opensciencegrid.org
          username: ${{ secrets.OSG_HARBOR_ROBOT_USER  }}
          password: ${{ secrets.OSG_HARBOR_ROBOT_PASSWORD }}
