name: Build ML platform image

on:
  push:
    branches:
      - "OctUpgrade"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1

      - name: Docker Build & Push Action
        uses: mr-smithers-excellent/docker-build-push@v6.4
        with:
          image: usatlas/ml-platform
          tags: oct_upgrade, ${{ github.sha }}
          registry: hub.opensciencegrid.org
          username: ${{ secrets.OSG_HARBOR_ROBOT_USER  }}
          password: ${{ secrets.OSG_HARBOR_ROBOT_PASSWORD }}
